### ISSUE TITLE
Copying using xclip not showing as image

### ISSUE THREAD

**Issue by ghost** [SUPERCILEX/clipboard-history#39]
Hi. Thank you for this awesome tool. 
The problem I'm having is that when I copy an image file using xclip, it doesn't appear as an image in the TUI app.
It just shows as "`Unable to display format of type "".`"

You should be able to reproduce it by using the following command:
`xclip -selection clipboard -t image/png -i A_PICTURE_FILE.png`

**Comment by SUPERCILEX** [comment]
Apologies for the delay, I was able to reproduce this. Unfortunately, I believe it's a compositor bug as running `xclip -selection clipboard -t UTF8_STRING -o` returns data instead of erroring out. But `xclip -selection clipboard -t TARGETS -o` correctly says there's just image/png.

The watcher works by first querying for UTF8_STRING assuming that the vast majority of what you copy is text, and only if that query fails do we query for targets and then pick the appropriate one.

How much of an annoyance would it be to use the ringboard CLI? You can do `ringboard add foo.png` and it'll Just Work™️. If that breaks your workflow, I can consider adding a config option to disable the fast path query which would fix this bug at the cost of being a little slower every other time.

**Comment by SUPERCILEX** [comment]
What if I added a flag to the ringboard CLI that made it put the contents in the system clipboard too? So you could run `maim -s | ringboard add -m image/png --copy`?

**Comment by SUPERCILEX** [comment]
It is, but the cli can tell the watcher to offer a file for pasting.

**Comment by SUPERCILEX** [comment]
I'm going to dog food this through next week and then I'll make a release assuming all goes well.

**Comment by SUPERCILEX** [comment]
Released! https://github.com/SUPERCILEX/clipboard-history/releases/tag/0.7.0
